version: "3"

services:
  aws:
    image: kukushkin/goaws:latest
    ports:
      - "4100:4100"

  postgres:
    image: postgres:12
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: test
      POSTGRES_DB: pubsub
    volumes:
      - ./scripts:/scripts