version: "3"

services:
# localstack:
#   image: localstack/localstack:latest
#   ports:
#     - 4566:4566
#   environment:
#     #- DEBUG=1
#     - SERVICES=sqs,sns
#     - START_WEB=0

  aws:
    image: kukushkin/goaws:latest
    ports:
      - 4100:4100

#  pulsar:
#    image: apachepulsar/pulsar:2.7.0
#    command: "bin/pulsar standalone"
#    ports:
#      - 6650:6650
#      - 8080:8080
#    volumes:
#      - $PWD/.data/pulsar:/pulsar/data
